# Generated by Django 3.1.6 on 2021-04-25 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent', models.CharField(max_length=60)),
                ('map', models.CharField(max_length=60)),
                ('ability', models.CharField(max_length=60)),
                ('agentLocation', models.CharField(max_length=60)),
                ('abilitySite', models.CharField(max_length=60)),
                ('abilityLocation', models.CharField(max_length=60)),
                ('side', models.BooleanField()),
            ],
        ),
    ]
