# Generated by Django 3.1.6 on 2022-01-04 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lineup',
            fields=[
                ('lineup_id', models.AutoField(primary_key=True, serialize=False)),
                ('agent', models.CharField(default='', max_length=60)),
                ('gameMap', models.CharField(default='', max_length=60)),
                ('ability', models.CharField(default='', max_length=60)),
                ('side', models.CharField(default='', max_length=60)),
                ('roundPhase', models.CharField(default='', max_length=60)),
                ('agentLocation', models.CharField(default='', max_length=60)),
                ('agentX', models.FloatField(default=0)),
                ('agentY', models.FloatField(default=0)),
                ('abilitySite', models.CharField(default='', max_length=60)),
                ('abilityLocation', models.CharField(default='', max_length=60)),
                ('abilityX', models.FloatField(default=0)),
                ('abilityY', models.FloatField(default=0)),
                ('url', models.CharField(default='', max_length=200)),
            ],
        ),
    ]
