# Generated by Django 3.1.5 on 2021-04-26 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valineupsapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineup',
            old_name='map',
            new_name='gameMap',
        ),
    ]
