# Generated by Django 3.1.6 on 2022-01-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valineupsapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineup',
            name='abilityLocationUrl',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='lineup',
            name='agentLocationUrl',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='lineup',
            name='crosshairUrl',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
