# Generated by Django 3.1.6 on 2021-05-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valineupsapi', '0002_auto_20210426_1421'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineup',
            name='side',
        ),
        migrations.AddField(
            model_name='lineup',
            name='end',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lineup',
            name='gamePhase',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AddField(
            model_name='lineup',
            name='start',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lineup',
            name='url',
            field=models.CharField(default='', max_length=200),
        ),
    ]
