# Generated by Django 3.1.6 on 2021-11-04 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valineupsapi', '0004_auto_20211102_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineup',
            old_name='id',
            new_name='lineup_id',
        ),
    ]
