# Generated by Django 3.1.6 on 2021-12-29 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valineupsapi', '0005_auto_20211104_1758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineup',
            old_name='gamePhase',
            new_name='roundPhase',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='end',
        ),
        migrations.RemoveField(
            model_name='lineup',
            name='start',
        ),
        migrations.AddField(
            model_name='lineup',
            name='abilityX',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lineup',
            name='abilityY',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lineup',
            name='agentX',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lineup',
            name='agentY',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lineup',
            name='side',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='ability',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='abilityLocation',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='abilitySite',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='agent',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='agentLocation',
            field=models.CharField(default='', max_length=60),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='gameMap',
            field=models.CharField(default='', max_length=60),
        ),
    ]
