# Generated by Django 3.1.6 on 2021-12-29 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valineupsapi', '0006_auto_20211229_0249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineup',
            name='abilityX',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='lineup',
            name='abilityY',
            field=models.FloatField(default=0),
        ),
    ]
